# Generated by Django 3.0.5 on 2020-05-07 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200507_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=500, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст ответа на e-mail')),
                ('sending_time', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('email_adress', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
