# Generated by Django 3.0.5 on 2020-05-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_newsletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='catalog_cus_email_05817a_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['verified'], name='catalog_cus_verifie_11392c_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='catalog_cus_usernam_eeb76e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['password'], name='catalog_cus_passwor_e0e460_idx'),
        ),
        migrations.AddIndex(
            model_name='places',
            index=models.Index(fields=['name'], name='catalog_pla_name_1c0b03_idx'),
        ),
    ]
