# Generated by Django 3.0.5 on 2020-05-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200521_0939'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='catalog_cus_passwor_e0e460_idx',
        ),
    ]
